### ISSUE TITLE
CheckboxWithLabel- Yup

### ISSUE THREAD

**Issue by Jippay** [stackworx/formik-material-ui#120]
Hi,
The label does not appear, nor the error message ... I need help please please

```
import React from 'react'
import { Formik, Field, Form } from 'formik'
import { TextField, CheckboxWithLabel } from 'formik-material-ui'
import * as Yup from 'yup'

const SignupForm = () => {
  return (
<Formik
      initialValues={{ accept: false }}
      validationSchema={Yup.object({
        accept: Yup.boolean()
          .required('Requis')
          .oneOf([true], "Error")
      })}

<Form>
        <Field
          name='accept'
          label='condition'
          type='checkbox'
          component={CheckboxWithLabel}
        />
</Form>
</Formik>
  )
}

export default SignupForm
```

**Comment by vegtelenseg** [comment]
Hello,

Here is an example that shows the checkbox and the label.

https://codesandbox.io/s/blissful-bird-vgobx

**Comment by Jippay** [comment]
> 
> 
> Hello,
> 
> Here is an example that shows the checkbox and the label.
> 
> https://codesandbox.io/s/blissful-bird-vgobx

Thank you ! Indeed, the label is displayed now, but validation with Yup does not display the error message ... Any idea how?

**Comment by cliedeman** [comment]
@Jippay you will need to include a [FormHelperText](https://material-ui.com/api/form-helper-text/) component to render the error.

**Comment by mjdeale** [comment]
@vegtelenseg @Jippay @cliedeman:

The solution above is NOT using the CheckboxWithLabel code to put the label up.  It is simply wrapping a label around a CheckboxWithLabel that failed to put a label up, using the FormControlLabel functionality.

I believe the confusion is caused because the sample code in the API documentation is wrong.  It shows:

<CheckboxWithLabel name="checked" label="Checkbox" />;

^^^^^ which doesn't work.

What does work is:

<CheckboxWithLabel name="checked" Label={{ label: "Checkbox" }} />

I am not sure if the right thing to do is to change the CheckboxWithLabel component, or the documentation, but clearly changing the documentation would clear up the confusion that exists right now.

-- M

**Comment by gone** [comment]
Although I've been successful in getting the label to appear:
```

                            <Field
                                fullWidth
                                component={CheckboxWithLabel}
                                name="tos"
                                type="checkbox"
                                Label={{
                                    label: (
                                        <>
                                            You accept our <Link href="/terms">TOS</Link>
                                        </>
                                    ),
                                }}
                            />
```

 the yup validation message is missing. Anything missing to get it to show up?

**Comment by wichert** [comment]
I ended up doing this:

```jsx
const tosError = formikBag.getFieldMeta('acceptTos').error

return (
  <Field
    component={CheckboxWithLabel}
    type="checkbox"
    name="acceptTos"
    Label={{ label: "I accept the terms and conditions" }}
    color="primary"
  />
  {tosError ? <FormHelperText error>{tosError}</FormHelperText>:null}
)
```
