### ISSUE TITLE
Select onChange does not work

### ISSUE THREAD

**Issue by leonbloy** [stackworx/formik-material-ui#183]
I cannot make `onChange` handler work with `Select`

This example on [codesanbox](https://codesandbox.io/s/distracted-borg-6cvwn?file=/src/App.js) shows three selects, 1 with formik-material-ui, 2 with plain Material UI and 3 without MUI. The eventHandler doesn't work for formik-material-u

**Comment by cliedeman** [comment]
Related to https://github.com/stackworx/formik-material-ui/pull/164

I need to think about how to solve this because `onChange` exists on both Field and Select

**Comment by leonbloy** [comment]
I ended writing my own wrapper, which receives an (optional) onChange in props and then...

```
     <Field
          name={name}
        >
          {({ field, form, meta }) => (
                ....
                <SelectMUI
                  label={label}
                  name={field.name}
                 value={field.value}
                 onBlur={field.onBlur}
                 onChange={e => { field.onChange(e); if (onChange) onChange(e); }}
               ...
```

**Comment by simonkaspersen** [comment]
Any workarounds or solutions?

**Comment by cliedeman** [comment]
@simonkaspersen 

you can import the `fieldToAutocomplete` function and create a custom component like [here](https://stackworx.github.io/formik-material-ui/docs/guide/custom-component#upper-casing-field)

**Comment by cliedeman** [comment]
This will be fixed by https://github.com/stackworx/formik-material-ui/pull/193

**Comment by semy** [comment]
@cliedeman When you will release this changes?

**Comment by cliedeman** [comment]
@semy I just published this as 3.0.0-alpha.0. Please give it a try

**Comment by DewangS** [comment]
@cliedeman I've tested this onChange and while works with ver.3.0.0, it's flaky. In my case I have a selection list of various payment types and my requirement is to DISPLAY selected payment method TEXT\DESCRIPTION on another page. So, basically I need to capture both for the selected payment from the dropdown list i.e. Payment Method ID and the payment method name (actual text which appears on the list). What I found is, the selection doesn't get retained i.e. after the **onChange event the selection resets back to my 0th element which is "Select payment method..."**. As I use Yup validation, I get an error stating that user MUST select a valid Payment Method. 

Also, while here, is there any way I can extract the display value of the selected item i.e. when user changes the selection? instead of going through this onChange event ? So far I can only get hold of the 'key' value in 'validate' event. This will save me from using lodash find etc.

So, here is my scenario, I've an array of JSON objects (just key value pairs), see below ..

```
paymentMethods = [
{"1", "Cash"},
{"2", "Credit Card"},
{"3", "Bank Transfer"}
]
```

Below is my state element within my functional component ...

`const [selectedPaymentMethod, setSelectedPaymentMethod] = useState("");`

My onChange function and SELECT element looks like below .... I am using lodash to find the selected payment method fro the JSON object array and populate the **selectedPaymentMethod** (see above) state element


```
function setPaymentType(ID) {
    console.log("+++ Selected PAYMENT METHOD : ",_.find(props.paymentMethods, ["value", ID]).key);
    setSelectedPaymentMethod(_.find(props.paymentMethods, ["value", ID]).key);
  }


<FormControl fullWidth>
                <InputLabel htmlFor="paymentMethod">Payment Method</InputLabel>
                <Field
                  component={Select}
                  type="Text"
                  name="paymentMethodID"
                  onChange={e => {setPaymentType(e.target.value)} }
                  inputProps={{
                    id: "paymentMethodID",
                  }}
                >
                  <MenuItem value="0">Select Payment Method...</MenuItem>
                  {props.paymentMethods.map((option) => (
                    <MenuItem value={option.value} key={option.key}>
                      {option.key}
                    </MenuItem>
                  ))}
                </Field>
                <FormHelperText error>
                  <ErrorMessage name="paymentMethodID" />
                </FormHelperText>
              </FormControl>
```

**Comment by cliedeman** [comment]
@DewangS could you please fork the codesandbox and add this example so I can take a look?
https://codesandbox.io/s/915qlr56rp

**Comment by DewangS** [comment]
@cliedeman done! please refer to [https://codesandbox.io/s/lucid-payne-ysufn?file=/src/payment.jsx](https://codesandbox.io/s/lucid-payne-ysufn?file=/src/payment.jsx)

if you comment out both onChange calls, the selection gets retained. Hope this helps.

**Comment by DewangS** [comment]
@cliedeman did you try the code snippet? any idea when this will be fixed?

**Comment by cliedeman** [comment]
@DewangS I have fixed the example

https://codesandbox.io/s/loving-glade-rjtoh?file=/src/payment.tsx

If you override the on change handler you need to manually update formik:

```
                        onChange={(e: any) => {
                          setPaymentType(e.target.value);
                          setFieldValue('paymentMethodID', e.target.value);
                        }}
```

**Comment by DewangS** [comment]
Thanks @cliedeman will try this later
