### ISSUE TITLE
Getting a warning when using TextField

### ISSUE THREAD

**Issue by SamuelHassine** [stackworx/formik-material-ui#45]
Hello,

When using the `TextField` in the last version, I am getting the following _warning_:

> Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.

Versions:
```
"react": "^16.5.2",
"@material-ui/core": "^3.4.0",
"formik-material-ui": "^0.0.14"
```

**Comment by cliedeman** [comment]
Hello,

That error usually means you have not provided a default value in `<Formik initialValues={...} ... />` and when you start typing the component is switching from controller to [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html).

Ciaran

**Comment by Philipp91** [comment]
Is it necessary to provide an entry in `initialValues` for each and every field? When there are no real initial values, it seems much more natural, simple and maintainable to just specify `initialValues={}`.

`formik-material-ui` could handle this case easily by replacing incoming `undefined` with a reasonable default value. That's an empty string for text fields (to ensure that they are controlled components, and because `null` isn't allowed there), and probably `null` for select-type components.
