### ISSUE TITLE
Errors not shown if field hasn't be touched on form submission

### ISSUE THREAD

**Issue by alexisab** [stackworx/formik-material-ui#69]
Hi !

I'm creating a "sign in" form and I noticed that if I submit the form without touching any fields, no errors are shown ... It's because of this line : https://github.com/stackworx/formik-material-ui/blob/8d8b6abf18e6ce9f95020eb6f9ce9f9c6b6b8e10/src/TextField.tsx#L23

If the field is "pristine" the lib doesn't show the error message, even after a submission.

It would be nice if the lib could display errors during submission even if the fields are pristine

**Comment by cliedeman** [comment]
Hi there, not sure if the behaviour changed in formik but submit changes fields to be `touched`

Sample here: https://codesandbox.io/s/r1lm9wlxk4

**Comment by mikew** [comment]
I noticed similar behaviour in the project I'm working on. In case anyone comes across this in the future, it was due to the fields being absent in the `initialValues` passed to `<Formik>`.

Still tho, Formik does set the error on submit, so it does seem like a discrepancy. https://codesandbox.io/s/polished-lake-nhz3d
